version: '3.4'

services:
  api:
    build:
      context: ./ApiClothes  # Ścieżka do folderu z aplikacją (ApiClothes)
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=YourDatabaseName;User Id=sa;Password=yourStrong(!)Password;
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

volumes:
  sqlserver_data:
